import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.module.scss";
import TopBar from "./components/organisms/TopBar/TopBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const dummyMenuItems = [
    { label: "About the villa", href: "#about-the-villa" },
    { label: "Location", href: "#location" },
    { label: "Rooms", href: "#rooms" },
    { label: "Gallery", href: "#gallery" },
    { label: "Contact", href: "#contact" },
  ];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/experimental.css" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <TopBar logo={{ src: "/logo-villa-de-miguel.svg", alt: "Villa de Miguel - Where farm meets luxury" } as HTMLImageElement} menuItems={dummyMenuItems} menuButton={{ label: "Menu" }} />
        {children}
      </body>
    </html>
  );
}
